//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("AgendaDigitalModel", "FK_tbContactos_tbGrupo", "tbGrupo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AgendaDigital.datos.Modelo.tbGrupo), "tbContactos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AgendaDigital.datos.Modelo.tbContactos), true)]
[assembly: EdmRelationshipAttribute("AgendaDigitalModel", "FK_tbContactos_tbUsuarios", "tbUsuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AgendaDigital.datos.Modelo.tbUsuarios), "tbContactos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AgendaDigital.datos.Modelo.tbContactos), true)]
[assembly: EdmRelationshipAttribute("AgendaDigitalModel", "FK_tbCorreo_tbContactos", "tbContactos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AgendaDigital.datos.Modelo.tbContactos), "tbCorreo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AgendaDigital.datos.Modelo.tbCorreo), true)]
[assembly: EdmRelationshipAttribute("AgendaDigitalModel", "FK_tbDireccion_tbContactos", "tbContactos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AgendaDigital.datos.Modelo.tbContactos), "tbDireccion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AgendaDigital.datos.Modelo.tbDireccion), true)]
[assembly: EdmRelationshipAttribute("AgendaDigitalModel", "FK_tbTelefono_tbContactos", "tbContactos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AgendaDigital.datos.Modelo.tbContactos), "tbTelefono", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AgendaDigital.datos.Modelo.tbTelefono), true)]

#endregion

namespace AgendaDigital.datos.Modelo
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class AgendaDigitalEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto AgendaDigitalEntities usando la cadena de conexión encontrada en la sección 'AgendaDigitalEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public AgendaDigitalEntities() : base("name=AgendaDigitalEntities", "AgendaDigitalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto AgendaDigitalEntities.
        /// </summary>
        public AgendaDigitalEntities(string connectionString) : base(connectionString, "AgendaDigitalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto AgendaDigitalEntities.
        /// </summary>
        public AgendaDigitalEntities(EntityConnection connection) : base(connection, "AgendaDigitalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tbContactos> tbContactos
        {
            get
            {
                if ((_tbContactos == null))
                {
                    _tbContactos = base.CreateObjectSet<tbContactos>("tbContactos");
                }
                return _tbContactos;
            }
        }
        private ObjectSet<tbContactos> _tbContactos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tbCorreo> tbCorreo
        {
            get
            {
                if ((_tbCorreo == null))
                {
                    _tbCorreo = base.CreateObjectSet<tbCorreo>("tbCorreo");
                }
                return _tbCorreo;
            }
        }
        private ObjectSet<tbCorreo> _tbCorreo;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tbDireccion> tbDireccion
        {
            get
            {
                if ((_tbDireccion == null))
                {
                    _tbDireccion = base.CreateObjectSet<tbDireccion>("tbDireccion");
                }
                return _tbDireccion;
            }
        }
        private ObjectSet<tbDireccion> _tbDireccion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tbGrupo> tbGrupo
        {
            get
            {
                if ((_tbGrupo == null))
                {
                    _tbGrupo = base.CreateObjectSet<tbGrupo>("tbGrupo");
                }
                return _tbGrupo;
            }
        }
        private ObjectSet<tbGrupo> _tbGrupo;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tbTelefono> tbTelefono
        {
            get
            {
                if ((_tbTelefono == null))
                {
                    _tbTelefono = base.CreateObjectSet<tbTelefono>("tbTelefono");
                }
                return _tbTelefono;
            }
        }
        private ObjectSet<tbTelefono> _tbTelefono;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tbUsuarios> tbUsuarios
        {
            get
            {
                if ((_tbUsuarios == null))
                {
                    _tbUsuarios = base.CreateObjectSet<tbUsuarios>("tbUsuarios");
                }
                return _tbUsuarios;
            }
        }
        private ObjectSet<tbUsuarios> _tbUsuarios;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tbContactos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotbContactos(tbContactos tbContactos)
        {
            base.AddObject("tbContactos", tbContactos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tbCorreo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotbCorreo(tbCorreo tbCorreo)
        {
            base.AddObject("tbCorreo", tbCorreo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tbDireccion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotbDireccion(tbDireccion tbDireccion)
        {
            base.AddObject("tbDireccion", tbDireccion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tbGrupo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotbGrupo(tbGrupo tbGrupo)
        {
            base.AddObject("tbGrupo", tbGrupo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tbTelefono. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotbTelefono(tbTelefono tbTelefono)
        {
            base.AddObject("tbTelefono", tbTelefono);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tbUsuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotbUsuarios(tbUsuarios tbUsuarios)
        {
            base.AddObject("tbUsuarios", tbUsuarios);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgendaDigitalModel", Name="tbContactos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbContactos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tbContactos.
        /// </summary>
        /// <param name="idContactos">Valor inicial de la propiedad idContactos.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        public static tbContactos CreatetbContactos(global::System.Int32 idContactos, global::System.String nombre)
        {
            tbContactos tbContactos = new tbContactos();
            tbContactos.idContactos = idContactos;
            tbContactos.nombre = nombre;
            return tbContactos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idContactos
        {
            get
            {
                return _idContactos;
            }
            set
            {
                if (_idContactos != value)
                {
                    OnidContactosChanging(value);
                    ReportPropertyChanging("idContactos");
                    _idContactos = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idContactos");
                    OnidContactosChanged();
                }
            }
        }
        private global::System.Int32 _idContactos;
        partial void OnidContactosChanging(global::System.Int32 value);
        partial void OnidContactosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idUsuario
        {
            get
            {
                return _idUsuario;
            }
            set
            {
                OnidUsuarioChanging(value);
                ReportPropertyChanging("idUsuario");
                _idUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idUsuario");
                OnidUsuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _idUsuario;
        partial void OnidUsuarioChanging(Nullable<global::System.Int32> value);
        partial void OnidUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idGrupo
        {
            get
            {
                return _idGrupo;
            }
            set
            {
                OnidGrupoChanging(value);
                ReportPropertyChanging("idGrupo");
                _idGrupo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idGrupo");
                OnidGrupoChanged();
            }
        }
        private Nullable<global::System.Int32> _idGrupo;
        partial void OnidGrupoChanging(Nullable<global::System.Int32> value);
        partial void OnidGrupoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> titulo
        {
            get
            {
                return _titulo;
            }
            set
            {
                OntituloChanging(value);
                ReportPropertyChanging("titulo");
                _titulo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("titulo");
                OntituloChanged();
            }
        }
        private Nullable<global::System.Int32> _titulo;
        partial void OntituloChanging(Nullable<global::System.Int32> value);
        partial void OntituloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellidos
        {
            get
            {
                return _apellidos;
            }
            set
            {
                OnapellidosChanging(value);
                ReportPropertyChanging("apellidos");
                _apellidos = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellidos");
                OnapellidosChanged();
            }
        }
        private global::System.String _apellidos;
        partial void OnapellidosChanging(global::System.String value);
        partial void OnapellidosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String empresa
        {
            get
            {
                return _empresa;
            }
            set
            {
                OnempresaChanging(value);
                ReportPropertyChanging("empresa");
                _empresa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("empresa");
                OnempresaChanged();
            }
        }
        private global::System.String _empresa;
        partial void OnempresaChanging(global::System.String value);
        partial void OnempresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> favorito
        {
            get
            {
                return _favorito;
            }
            set
            {
                OnfavoritoChanging(value);
                ReportPropertyChanging("favorito");
                _favorito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("favorito");
                OnfavoritoChanged();
            }
        }
        private Nullable<global::System.Boolean> _favorito;
        partial void OnfavoritoChanging(Nullable<global::System.Boolean> value);
        partial void OnfavoritoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgendaDigitalModel", "FK_tbContactos_tbGrupo", "tbGrupo")]
        public tbGrupo tbGrupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbGrupo>("AgendaDigitalModel.FK_tbContactos_tbGrupo", "tbGrupo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbGrupo>("AgendaDigitalModel.FK_tbContactos_tbGrupo", "tbGrupo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbGrupo> tbGrupoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbGrupo>("AgendaDigitalModel.FK_tbContactos_tbGrupo", "tbGrupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbGrupo>("AgendaDigitalModel.FK_tbContactos_tbGrupo", "tbGrupo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgendaDigitalModel", "FK_tbContactos_tbUsuarios", "tbUsuarios")]
        public tbUsuarios tbUsuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbUsuarios>("AgendaDigitalModel.FK_tbContactos_tbUsuarios", "tbUsuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbUsuarios>("AgendaDigitalModel.FK_tbContactos_tbUsuarios", "tbUsuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbUsuarios> tbUsuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbUsuarios>("AgendaDigitalModel.FK_tbContactos_tbUsuarios", "tbUsuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbUsuarios>("AgendaDigitalModel.FK_tbContactos_tbUsuarios", "tbUsuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgendaDigitalModel", "FK_tbCorreo_tbContactos", "tbCorreo")]
        public EntityCollection<tbCorreo> tbCorreo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbCorreo>("AgendaDigitalModel.FK_tbCorreo_tbContactos", "tbCorreo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbCorreo>("AgendaDigitalModel.FK_tbCorreo_tbContactos", "tbCorreo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgendaDigitalModel", "FK_tbDireccion_tbContactos", "tbDireccion")]
        public EntityCollection<tbDireccion> tbDireccion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbDireccion>("AgendaDigitalModel.FK_tbDireccion_tbContactos", "tbDireccion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbDireccion>("AgendaDigitalModel.FK_tbDireccion_tbContactos", "tbDireccion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgendaDigitalModel", "FK_tbTelefono_tbContactos", "tbTelefono")]
        public EntityCollection<tbTelefono> tbTelefono
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbTelefono>("AgendaDigitalModel.FK_tbTelefono_tbContactos", "tbTelefono");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbTelefono>("AgendaDigitalModel.FK_tbTelefono_tbContactos", "tbTelefono", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgendaDigitalModel", Name="tbCorreo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbCorreo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tbCorreo.
        /// </summary>
        /// <param name="idCorreo">Valor inicial de la propiedad idCorreo.</param>
        /// <param name="correo">Valor inicial de la propiedad correo.</param>
        /// <param name="idContactos">Valor inicial de la propiedad idContactos.</param>
        public static tbCorreo CreatetbCorreo(global::System.Int32 idCorreo, global::System.String correo, global::System.Int32 idContactos)
        {
            tbCorreo tbCorreo = new tbCorreo();
            tbCorreo.idCorreo = idCorreo;
            tbCorreo.correo = correo;
            tbCorreo.idContactos = idContactos;
            return tbCorreo;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCorreo
        {
            get
            {
                return _idCorreo;
            }
            set
            {
                if (_idCorreo != value)
                {
                    OnidCorreoChanging(value);
                    ReportPropertyChanging("idCorreo");
                    _idCorreo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idCorreo");
                    OnidCorreoChanged();
                }
            }
        }
        private global::System.Int32 _idCorreo;
        partial void OnidCorreoChanging(global::System.Int32 value);
        partial void OnidCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private Nullable<global::System.Int32> _tipo;
        partial void OntipoChanging(Nullable<global::System.Int32> value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String correo
        {
            get
            {
                return _correo;
            }
            set
            {
                OncorreoChanging(value);
                ReportPropertyChanging("correo");
                _correo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("correo");
                OncorreoChanged();
            }
        }
        private global::System.String _correo;
        partial void OncorreoChanging(global::System.String value);
        partial void OncorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idContactos
        {
            get
            {
                return _idContactos;
            }
            set
            {
                OnidContactosChanging(value);
                ReportPropertyChanging("idContactos");
                _idContactos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idContactos");
                OnidContactosChanged();
            }
        }
        private global::System.Int32 _idContactos;
        partial void OnidContactosChanging(global::System.Int32 value);
        partial void OnidContactosChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgendaDigitalModel", "FK_tbCorreo_tbContactos", "tbContactos")]
        public tbContactos tbContactos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbCorreo_tbContactos", "tbContactos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbCorreo_tbContactos", "tbContactos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbContactos> tbContactosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbCorreo_tbContactos", "tbContactos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbCorreo_tbContactos", "tbContactos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgendaDigitalModel", Name="tbDireccion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbDireccion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tbDireccion.
        /// </summary>
        /// <param name="idDireccion">Valor inicial de la propiedad idDireccion.</param>
        /// <param name="direccion">Valor inicial de la propiedad direccion.</param>
        /// <param name="idContactos">Valor inicial de la propiedad idContactos.</param>
        public static tbDireccion CreatetbDireccion(global::System.Int32 idDireccion, global::System.String direccion, global::System.Int32 idContactos)
        {
            tbDireccion tbDireccion = new tbDireccion();
            tbDireccion.idDireccion = idDireccion;
            tbDireccion.direccion = direccion;
            tbDireccion.idContactos = idContactos;
            return tbDireccion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idDireccion
        {
            get
            {
                return _idDireccion;
            }
            set
            {
                if (_idDireccion != value)
                {
                    OnidDireccionChanging(value);
                    ReportPropertyChanging("idDireccion");
                    _idDireccion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idDireccion");
                    OnidDireccionChanged();
                }
            }
        }
        private global::System.Int32 _idDireccion;
        partial void OnidDireccionChanging(global::System.Int32 value);
        partial void OnidDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private Nullable<global::System.Int32> _tipo;
        partial void OntipoChanging(Nullable<global::System.Int32> value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idContactos
        {
            get
            {
                return _idContactos;
            }
            set
            {
                OnidContactosChanging(value);
                ReportPropertyChanging("idContactos");
                _idContactos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idContactos");
                OnidContactosChanged();
            }
        }
        private global::System.Int32 _idContactos;
        partial void OnidContactosChanging(global::System.Int32 value);
        partial void OnidContactosChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgendaDigitalModel", "FK_tbDireccion_tbContactos", "tbContactos")]
        public tbContactos tbContactos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbDireccion_tbContactos", "tbContactos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbDireccion_tbContactos", "tbContactos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbContactos> tbContactosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbDireccion_tbContactos", "tbContactos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbDireccion_tbContactos", "tbContactos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgendaDigitalModel", Name="tbGrupo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbGrupo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tbGrupo.
        /// </summary>
        /// <param name="idGrupo">Valor inicial de la propiedad idGrupo.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        public static tbGrupo CreatetbGrupo(global::System.Int32 idGrupo, global::System.String nombre)
        {
            tbGrupo tbGrupo = new tbGrupo();
            tbGrupo.idGrupo = idGrupo;
            tbGrupo.nombre = nombre;
            return tbGrupo;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idGrupo
        {
            get
            {
                return _idGrupo;
            }
            set
            {
                if (_idGrupo != value)
                {
                    OnidGrupoChanging(value);
                    ReportPropertyChanging("idGrupo");
                    _idGrupo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idGrupo");
                    OnidGrupoChanged();
                }
            }
        }
        private global::System.Int32 _idGrupo;
        partial void OnidGrupoChanging(global::System.Int32 value);
        partial void OnidGrupoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _estado;
        partial void OnestadoChanging(Nullable<global::System.Boolean> value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgendaDigitalModel", "FK_tbContactos_tbGrupo", "tbContactos")]
        public EntityCollection<tbContactos> tbContactos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbContactos>("AgendaDigitalModel.FK_tbContactos_tbGrupo", "tbContactos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbContactos>("AgendaDigitalModel.FK_tbContactos_tbGrupo", "tbContactos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgendaDigitalModel", Name="tbTelefono")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbTelefono : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tbTelefono.
        /// </summary>
        /// <param name="idTelefono">Valor inicial de la propiedad idTelefono.</param>
        /// <param name="telefono">Valor inicial de la propiedad telefono.</param>
        /// <param name="idContactos">Valor inicial de la propiedad idContactos.</param>
        public static tbTelefono CreatetbTelefono(global::System.Int32 idTelefono, global::System.String telefono, global::System.Int32 idContactos)
        {
            tbTelefono tbTelefono = new tbTelefono();
            tbTelefono.idTelefono = idTelefono;
            tbTelefono.telefono = telefono;
            tbTelefono.idContactos = idContactos;
            return tbTelefono;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTelefono
        {
            get
            {
                return _idTelefono;
            }
            set
            {
                if (_idTelefono != value)
                {
                    OnidTelefonoChanging(value);
                    ReportPropertyChanging("idTelefono");
                    _idTelefono = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTelefono");
                    OnidTelefonoChanged();
                }
            }
        }
        private global::System.Int32 _idTelefono;
        partial void OnidTelefonoChanging(global::System.Int32 value);
        partial void OnidTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private Nullable<global::System.Int32> _tipo;
        partial void OntipoChanging(Nullable<global::System.Int32> value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.String _telefono;
        partial void OntelefonoChanging(global::System.String value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idContactos
        {
            get
            {
                return _idContactos;
            }
            set
            {
                OnidContactosChanging(value);
                ReportPropertyChanging("idContactos");
                _idContactos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idContactos");
                OnidContactosChanged();
            }
        }
        private global::System.Int32 _idContactos;
        partial void OnidContactosChanging(global::System.Int32 value);
        partial void OnidContactosChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgendaDigitalModel", "FK_tbTelefono_tbContactos", "tbContactos")]
        public tbContactos tbContactos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbTelefono_tbContactos", "tbContactos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbTelefono_tbContactos", "tbContactos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbContactos> tbContactosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbTelefono_tbContactos", "tbContactos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbContactos>("AgendaDigitalModel.FK_tbTelefono_tbContactos", "tbContactos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgendaDigitalModel", Name="tbUsuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbUsuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tbUsuarios.
        /// </summary>
        /// <param name="idUsuario">Valor inicial de la propiedad idUsuario.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="password">Valor inicial de la propiedad password.</param>
        public static tbUsuarios CreatetbUsuarios(global::System.Int32 idUsuario, global::System.String nombre, global::System.String password)
        {
            tbUsuarios tbUsuarios = new tbUsuarios();
            tbUsuarios.idUsuario = idUsuario;
            tbUsuarios.nombre = nombre;
            tbUsuarios.password = password;
            return tbUsuarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idUsuario
        {
            get
            {
                return _idUsuario;
            }
            set
            {
                if (_idUsuario != value)
                {
                    OnidUsuarioChanging(value);
                    ReportPropertyChanging("idUsuario");
                    _idUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idUsuario");
                    OnidUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _idUsuario;
        partial void OnidUsuarioChanging(global::System.Int32 value);
        partial void OnidUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgendaDigitalModel", "FK_tbContactos_tbUsuarios", "tbContactos")]
        public EntityCollection<tbContactos> tbContactos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbContactos>("AgendaDigitalModel.FK_tbContactos_tbUsuarios", "tbContactos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbContactos>("AgendaDigitalModel.FK_tbContactos_tbUsuarios", "tbContactos", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
